// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: proto/test.proto

package dtproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestServiceClient interface {
	TestBidirectional(ctx context.Context, opts ...grpc.CallOption) (TestService_TestBidirectionalClient, error)
	TestUnidirectional(ctx context.Context, in *TestData, opts ...grpc.CallOption) (*TestResponse, error)
}

type testServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestServiceClient(cc grpc.ClientConnInterface) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) TestBidirectional(ctx context.Context, opts ...grpc.CallOption) (TestService_TestBidirectionalClient, error) {
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[0], "/ptproto.TestService/TestBidirectional", opts...)
	if err != nil {
		return nil, err
	}
	x := &testServiceTestBidirectionalClient{stream}
	return x, nil
}

type TestService_TestBidirectionalClient interface {
	Send(*TestData) error
	Recv() (*TestResponse, error)
	grpc.ClientStream
}

type testServiceTestBidirectionalClient struct {
	grpc.ClientStream
}

func (x *testServiceTestBidirectionalClient) Send(m *TestData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *testServiceTestBidirectionalClient) Recv() (*TestResponse, error) {
	m := new(TestResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *testServiceClient) TestUnidirectional(ctx context.Context, in *TestData, opts ...grpc.CallOption) (*TestResponse, error) {
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, "/ptproto.TestService/TestUnidirectional", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServiceServer is the server API for TestService service.
// All implementations should embed UnimplementedTestServiceServer
// for forward compatibility
type TestServiceServer interface {
	TestBidirectional(TestService_TestBidirectionalServer) error
	TestUnidirectional(context.Context, *TestData) (*TestResponse, error)
}

// UnimplementedTestServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTestServiceServer struct {
}

func (UnimplementedTestServiceServer) TestBidirectional(TestService_TestBidirectionalServer) error {
	return status.Errorf(codes.Unimplemented, "method TestBidirectional not implemented")
}
func (UnimplementedTestServiceServer) TestUnidirectional(context.Context, *TestData) (*TestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestUnidirectional not implemented")
}

// UnsafeTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServiceServer will
// result in compilation errors.
type UnsafeTestServiceServer interface {
	mustEmbedUnimplementedTestServiceServer()
}

func RegisterTestServiceServer(s grpc.ServiceRegistrar, srv TestServiceServer) {
	s.RegisterService(&TestService_ServiceDesc, srv)
}

func _TestService_TestBidirectional_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).TestBidirectional(&testServiceTestBidirectionalServer{stream})
}

type TestService_TestBidirectionalServer interface {
	Send(*TestResponse) error
	Recv() (*TestData, error)
	grpc.ServerStream
}

type testServiceTestBidirectionalServer struct {
	grpc.ServerStream
}

func (x *testServiceTestBidirectionalServer) Send(m *TestResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *testServiceTestBidirectionalServer) Recv() (*TestData, error) {
	m := new(TestData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TestService_TestUnidirectional_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).TestUnidirectional(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptproto.TestService/TestUnidirectional",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).TestUnidirectional(ctx, req.(*TestData))
	}
	return interceptor(ctx, in, info, handler)
}

// TestService_ServiceDesc is the grpc.ServiceDesc for TestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ptproto.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestUnidirectional",
			Handler:    _TestService_TestUnidirectional_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TestBidirectional",
			Handler:       _TestService_TestBidirectional_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/test.proto",
}
